title: fullam.net
name: Anthony Fullam
email:
description: "Personal website of Anthony Fullam."
twitter_username: Fullam_Anthony
github_username: fullama
minimal_mistakes_skin: default
search: true
words_per_minute: 200

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


author:
  name             : "Anthony Fullam"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Bioinformatics Software Engineer"
  location         : "Heidelberg, Germany"
  email            :
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Fullam_Anthony"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fullama/"
    - label: "Orcid"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0000-0002-0884-8124"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=X2CsjEIAAAAJ"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/anthony-fullam/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/Fullam_Anthony"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/fullama/"
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      url: "https://git.embl.de/fullam"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider               : "utterances"
  utterances:
    theme                : "github-light"
    issue_term           : "pathname"

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "G-N2BC96R915"

# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - "https://www.linkedin.com/in/anthony-fullam/"
    - "https://twitter.com/Fullam_Anthony"
    - "https://github.com/fullama/"
    - "fullam.net"
    - "https://scholar.google.com/citations?user=X2CsjEIAAAAJ"
    - "https://orcid.org/0000-0002-0884-8124"
    - "https://pubmed.ncbi.nlm.nih.gov/?term=Anthony+fullam&sort=date"
